version: "3.8"
services:
  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - inception-network
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always
  


  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always
    depends_on:
      - mariadb
  



  ngnix:
    build: ./requirements/nginx
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    
      
networks:
  inception-network:
    driver: bridge


volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/aragragu/data/wp_vol
      o: bind
  
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/aragragu/data/maria_vol
      o: bind
