services:
  mariadb:
    image: mariadb:aragragu
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception-network
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
  


  wordpress:
    image: wordpress:aragragu
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always
    depends_on:
      mariadb:
          condition: service_healthy

  



  nginx:
    image: ngnix:aragragu
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    
      
networks:
  inception-network:
    driver: bridge


volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/aragragu/data/wordpress_volume
      o: bind
  
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/aragragu/data/mariadb_volume
      o: bind
